# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppBehaviorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_ip', models.GenericIPAddressField()),
                ('app_name', models.CharField(max_length=30)),
                ('app_action', models.CharField(max_length=20)),
                ('target_url', models.URLField()),
                ('access_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WifiUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_ip', models.GenericIPAddressField()),
                ('wechat_id', models.CharField(max_length=40)),
                ('wechat_head_img', models.FilePathField()),
                ('os_type', models.CharField(max_length=10)),
                ('phone_num', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='appbehaviorlog',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheepwall_app.WifiUser'),
        ),
    ]
