# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheepwall_app', '0002_auto_20170305_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='appbehaviorlog',
            name='access_date',
            field=models.DateField(auto_now=True),
        ),
    ]
