# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheepwall_app', '0003_appbehaviorlog_access_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appbehaviorlog',
            options={'get_latest_by': 'access_time'},
        ),
    ]
