# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheepwall_app', '0007_auto_20170306_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='appbehaviorlog',
            name='app_account',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appbehaviorlog',
            name='app_content',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appbehaviorlog',
            name='app_keyword',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='appbehaviorlog',
            name='mail_from',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appbehaviorlog',
            name='mail_to',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appbehaviorlog',
            name='trans_filename',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='appbehaviorlog',
            name='access_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appbehaviorlog',
            name='app_action',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appbehaviorlog',
            name='app_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wifiuser',
            name='mac_addr',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wifiuser',
            name='os_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='wifiuser',
            name='phone_num',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='wifiuser',
            name='wechat_nickname',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
