# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheepwall_app', '0009_auto_20170308_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appbehaviorlog',
            name='app_content',
        ),
    ]
