# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheepwall_app', '0013_mobile_os_vulns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wechattolocalip',
            name='wifi_user',
        ),
        migrations.AddField(
            model_name='wifiuser',
            name='local_ip',
            field=models.GenericIPAddressField(default='1.1.1.1'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='WechatToLocalIP',
        ),
    ]
