# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheepwall_app', '0019_auto_20170320_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mac_IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(max_length=255, null=True)),
                ('Mac', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
